server:
  port: 80

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging:
  level:
    com.tradin.module.feign.client: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: INFO
      springframework: INFO

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /v1/**

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000

secret:
  aes-secret: ${AES_SECRET_KEY}
  cognito-client-id: ${COGNITO_CLIENT_ID}
  cognito-auth-redirect-uri: ${COGNITO_AUTH_REDIRECT_URI}
  cognito-issuer: ${COGNITO_ISSUER}
  swagger-username: ${SWAGGER_USERNAME}
  swagger-password: ${SWAGGER_PASSWORD}

